//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.House {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblhid;
	protected global::System.Web.UI.WebControls.Label lblcid;
	protected global::System.Web.UI.WebControls.Label lbluid;
	protected global::System.Web.UI.WebControls.Label lblsid;
		protected global::System.Web.UI.WebControls.TextBox txthname;
		protected global::System.Web.UI.WebControls.TextBox txthdescription;
		protected global::System.Web.UI.WebControls.TextBox txthmoney;
		protected global::System.Web.UI.WebControls.TextBox txthtype;
		protected global::System.Web.UI.WebControls.TextBox txthphotoone;
		protected global::System.Web.UI.WebControls.TextBox txthphototwo;
		protected global::System.Web.UI.WebControls.TextBox txthphotothree;
		protected global::System.Web.UI.WebControls.TextBox txthphotofour;
		protected global::System.Web.UI.WebControls.TextBox txthfloor;
		protected global::System.Web.UI.WebControls.TextBox txthsize;
		protected global::System.Web.UI.WebControls.TextBox txtharea;
		protected global::System.Web.UI.WebControls.TextBox txthcommunity;
		protected global::System.Web.UI.WebControls.TextBox txthadress;
		protected global::System.Web.UI.WebControls.TextBox txthtime;
		protected global::System.Web.UI.WebControls.TextBox txthmode;
		protected global::System.Web.UI.WebControls.TextBox txthstatus;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
