//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.House {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblhid;
	protected global::System.Web.UI.WebControls.Label lblcid;
	protected global::System.Web.UI.WebControls.Label lbluid;
	protected global::System.Web.UI.WebControls.Label lblsid;
	protected global::System.Web.UI.WebControls.Label lblhname;
	protected global::System.Web.UI.WebControls.Label lblhdescription;
	protected global::System.Web.UI.WebControls.Label lblhmoney;
	protected global::System.Web.UI.WebControls.Label lblhtype;
	protected global::System.Web.UI.WebControls.Label lblhphotoone;
	protected global::System.Web.UI.WebControls.Label lblhphototwo;
	protected global::System.Web.UI.WebControls.Label lblhphotothree;
	protected global::System.Web.UI.WebControls.Label lblhphotofour;
	protected global::System.Web.UI.WebControls.Label lblhfloor;
	protected global::System.Web.UI.WebControls.Label lblhsize;
	protected global::System.Web.UI.WebControls.Label lblharea;
	protected global::System.Web.UI.WebControls.Label lblhcommunity;
	protected global::System.Web.UI.WebControls.Label lblhadress;
	protected global::System.Web.UI.WebControls.Label lblhtime;
	protected global::System.Web.UI.WebControls.Label lblhmode;
	protected global::System.Web.UI.WebControls.Label lblhstatus;


       
    }
}
