//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.Contract {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuid;
		protected global::System.Web.UI.WebControls.TextBox txthid;
		protected global::System.Web.UI.WebControls.TextBox txtcname;
		protected global::System.Web.UI.WebControls.TextBox txtccontent;
		protected global::System.Web.UI.WebControls.TextBox txtcphoto;
		protected global::System.Web.UI.WebControls.TextBox txtcstatus;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
