//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.Contract {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcid;
	protected global::System.Web.UI.WebControls.Label lbluid;
	protected global::System.Web.UI.WebControls.Label lblhid;
	protected global::System.Web.UI.WebControls.Label lblcname;
	protected global::System.Web.UI.WebControls.Label lblccontent;
	protected global::System.Web.UI.WebControls.Label lblcphoto;
	protected global::System.Web.UI.WebControls.Label lblcstatus;


       
    }
}
