//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.Worker {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtwname;
		protected global::System.Web.UI.WebControls.TextBox txtwsex;
		protected global::System.Web.UI.WebControls.TextBox txtwphoto;
		protected global::System.Web.UI.WebControls.TextBox txtwcard;
		protected global::System.Web.UI.WebControls.TextBox txtwpassword;
		protected global::System.Web.UI.WebControls.TextBox txtwtel;
		protected global::System.Web.UI.WebControls.TextBox txtwemail;
		protected global::System.Web.UI.WebControls.TextBox txtwadress;
		protected global::System.Web.UI.WebControls.TextBox txtwtype;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
