//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.Worker {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblwid;
	protected global::System.Web.UI.WebControls.Label lblwname;
	protected global::System.Web.UI.WebControls.Label lblwsex;
	protected global::System.Web.UI.WebControls.Label lblwphoto;
	protected global::System.Web.UI.WebControls.Label lblwcard;
	protected global::System.Web.UI.WebControls.Label lblwpassword;
	protected global::System.Web.UI.WebControls.Label lblwtel;
	protected global::System.Web.UI.WebControls.Label lblwemail;
	protected global::System.Web.UI.WebControls.Label lblwadress;
	protected global::System.Web.UI.WebControls.Label lblwtype;


       
    }
}
