//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.User {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbluid;
		protected global::System.Web.UI.WebControls.TextBox txtunickname;
		protected global::System.Web.UI.WebControls.TextBox txtuname;
		protected global::System.Web.UI.WebControls.TextBox txtusex;
		protected global::System.Web.UI.WebControls.TextBox txtuphoto;
	protected global::System.Web.UI.WebControls.Label lblucard;
		protected global::System.Web.UI.WebControls.TextBox txtucardphoto;
		protected global::System.Web.UI.WebControls.TextBox txtupassword;
		protected global::System.Web.UI.WebControls.TextBox txtutel;
		protected global::System.Web.UI.WebControls.TextBox txtuqq;
		protected global::System.Web.UI.WebControls.TextBox txtuemail;
		protected global::System.Web.UI.WebControls.TextBox txturegtime;
		protected global::System.Web.UI.WebControls.TextBox txtucredit;
		protected global::System.Web.UI.WebControls.TextBox txtutype;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
