//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myhouse.Web.User {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluid;
	protected global::System.Web.UI.WebControls.Label lblunickname;
	protected global::System.Web.UI.WebControls.Label lbluname;
	protected global::System.Web.UI.WebControls.Label lblusex;
	protected global::System.Web.UI.WebControls.Label lbluphoto;
	protected global::System.Web.UI.WebControls.Label lblucard;
	protected global::System.Web.UI.WebControls.Label lblucardphoto;
	protected global::System.Web.UI.WebControls.Label lblupassword;
	protected global::System.Web.UI.WebControls.Label lblutel;
	protected global::System.Web.UI.WebControls.Label lbluqq;
	protected global::System.Web.UI.WebControls.Label lbluemail;
	protected global::System.Web.UI.WebControls.Label lbluregtime;
	protected global::System.Web.UI.WebControls.Label lblucredit;
	protected global::System.Web.UI.WebControls.Label lblutype;


       
    }
}
